apiVersion: apps/v1
kind: Deployment
metadata:
  name: 8byte-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 8byte-app
  template:
    metadata:
      labels:
        app: 8byte-app
    spec:
      containers:
      - name: 8byte-app
        image: 799442263888.dkr.ecr.us-east-1.amazonaws.com/8byte-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: rds-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-db-credentials
              key: password
